apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: invidious-infisical-secret
  namespace: invidious
spec:
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: infisical-operator
      secretsScope:
        envSlug: prod
        projectSlug: homelab-bz-gt
        recursive: false
        secretsPath: /
  hostAPI: https://infisical.sirddail.net/api
  managedSecretReference:
    creationPolicy: Owner
    secretName: invidious-secrets
    secretNamespace: invidious
    secretType: Opaque
    template:
      data:
        INVIDIOUS_HMAC_KEY: '{{ .INVIDIOUS_HMAC_KEY.Value }}'
        INVIDIOUS_COMPANION_KEY: '{{ .INVIDIOUS_COMPANION_KEY.Value }}'
      includeAllSecrets: false
  resyncInterval: 60
