apiVersion: v1
kind: Service
metadata:
  name: invidious
  namespace: invidious
  labels:
    app.kubernetes.io/name: invidious
    app.kubernetes.io/managed-by: argocd
spec:
  selector:
    app: invidious
  ports:
    - name: http
      port: 3000
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: invidious-companion
  namespace: invidious
  labels:
    app.kubernetes.io/name: invidious
    app.kubernetes.io/managed-by: argocd
spec:
  selector:
    app: invidious-companion
  ports:
    - name: http
      port: 8282
      targetPort: http
